// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Entities.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180202204644_SubProcesos")]
    partial class SubProcesos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direccion");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("ID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Entities.Insumo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Descripcion");

                    b.Property<int>("Stock");

                    b.HasKey("ID");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Entities.ItemSubProceso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<int>("InsumoID");

                    b.Property<decimal>("KgG");

                    b.Property<decimal>("Porcentaje");

                    b.Property<int?>("RecetaHumedaID");

                    b.Property<int>("SubProcesoID");

                    b.HasKey("ID");

                    b.HasIndex("InsumoID");

                    b.HasIndex("RecetaHumedaID");

                    b.HasIndex("SubProcesoID");

                    b.ToTable("ItemsReceta");
                });

            modelBuilder.Entity("Entities.Operario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("ID");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("Entities.Partida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CantSinClasificar");

                    b.Property<int>("Cantidad");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<string>("Observaciones");

                    b.Property<decimal>("PesoPromedio");

                    b.Property<string>("Tipo");

                    b.HasKey("ID");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Entities.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteID");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Entities.ProcesoHumedo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Fin");

                    b.Property<TimeSpan>("Inicio");

                    b.Property<int>("Proceso");

                    b.Property<int>("SubPartidaID");

                    b.HasKey("ID");

                    b.HasIndex("SubPartidaID");

                    b.ToTable("ProcesosHumedos");
                });

            modelBuilder.Entity("Entities.RecetaHumeda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProcesoHumedoID");

                    b.HasKey("ID");

                    b.HasIndex("ProcesoHumedoID")
                        .IsUnique();

                    b.ToTable("RecetaHumedas");
                });

            modelBuilder.Entity("Entities.SubPartida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calidad");

                    b.Property<int>("CantCueros");

                    b.Property<decimal?>("Eficiencia");

                    b.Property<string>("Estado");

                    b.Property<int>("PartidaID");

                    b.Property<int?>("PedidoID");

                    b.Property<int?>("Stock");

                    b.HasKey("ID");

                    b.HasIndex("PartidaID");

                    b.HasIndex("PedidoID")
                        .IsUnique()
                        .HasFilter("[PedidoID] IS NOT NULL");

                    b.ToTable("SubPartidas");
                });

            modelBuilder.Entity("Entities.SubProceso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Be");

                    b.Property<TimeSpan>("Fin");

                    b.Property<TimeSpan>("Inicio");

                    b.Property<string>("Nombre");

                    b.Property<string>("Observaciones");

                    b.Property<decimal>("Ph");

                    b.Property<int>("ProcesoHumedoID");

                    b.Property<int?>("RecetaHumedaID");

                    b.Property<int>("RecetaID");

                    b.Property<decimal>("Temp");

                    b.Property<TimeSpan>("Tiempo");

                    b.HasKey("ID");

                    b.HasIndex("ProcesoHumedoID");

                    b.HasIndex("RecetaHumedaID");

                    b.ToTable("SubProcesos");
                });

            modelBuilder.Entity("Entities.ItemSubProceso", b =>
                {
                    b.HasOne("Entities.Insumo", "Insumo")
                        .WithMany("ItemReceta")
                        .HasForeignKey("InsumoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.RecetaHumeda")
                        .WithMany("ItemsSubProcesos")
                        .HasForeignKey("RecetaHumedaID");

                    b.HasOne("Entities.SubProceso", "SubProceso")
                        .WithMany("ItemsSubProcesos")
                        .HasForeignKey("SubProcesoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Pedido", b =>
                {
                    b.HasOne("Entities.Cliente", "Cliente")
                        .WithMany("Pedido")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.ProcesoHumedo", b =>
                {
                    b.HasOne("Entities.SubPartida", "SubPartida")
                        .WithMany()
                        .HasForeignKey("SubPartidaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.RecetaHumeda", b =>
                {
                    b.HasOne("Entities.ProcesoHumedo", "ProcesoHumedo")
                        .WithOne("RecetaHumeda")
                        .HasForeignKey("Entities.RecetaHumeda", "ProcesoHumedoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.SubPartida", b =>
                {
                    b.HasOne("Entities.Partida", "Partida")
                        .WithMany("SubPartidas")
                        .HasForeignKey("PartidaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Pedido", "Pedido")
                        .WithOne("SubPartida")
                        .HasForeignKey("Entities.SubPartida", "PedidoID");
                });

            modelBuilder.Entity("Entities.SubProceso", b =>
                {
                    b.HasOne("Entities.ProcesoHumedo")
                        .WithMany("SubProcesos")
                        .HasForeignKey("ProcesoHumedoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.RecetaHumeda", "RecetaHumeda")
                        .WithMany()
                        .HasForeignKey("RecetaHumedaID");
                });
#pragma warning restore 612, 618
        }
    }
}
